config/routes.rb
Rails.application.routes.draw do
	resources :books
  resources :publication_houses
  resources :categories
  resources :authors
  resources :book_sales
	root to: 'books#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  validates :name, presence: true
  has_many :books
  belongs_to :publication_house
end

app/models/book.rb
class Book < ApplicationRecord
  validates :name, :publication_date, presence: true
  validates :price, numericality: true
  belongs_to :author
  belongs_to :category
  has_many :book_sales
end

app/models/book_sale.rb
class BookSale < ApplicationRecord
  belongs_to :book
end

app/models/category.rb
class Category < ApplicationRecord
  validates :cat_name, presence: true
end

app/models/publication_house.rb
class PublicationHouse < ApplicationRecord
  has_many :authors
  has_many :books, through: :authors
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :find_author, only: %i[show edit update destroy]

  def index
    @authors = Author.all    
  end

  def new
    @author = Author.new
    @publication_houses = PublicationHouse.all
  end

  def create
    @author = Author.new(author_params)
    if @author.save
      redirect_to authors_path
    else
      flash[:error] = @author.errors.full_messages.join(", ")
      redirect_to new_author_path
    end
  end

  def edit
    @publication_houses = PublicationHouse.all
  end

  def update
    if @author.update(author_params)
      redirect_to authors_path
    else
      @publication_houses = PublicationHouse.all
      render :edit
    end
  end

  def show
  end

  def destroy
    if @author.destroy
      redirect_to authors_path
    else
      redirect_to author_path
    end
  end

  private

  def author_params
    params.require(:author).permit(:name, :address, :pen_name, :dob, :phone, :publication_house_id)
  end

  def permitted_params
    params.permit(:id)
  end

  def find_author
    @author = Author.find permitted_params['id']
  end
end

app/controllers/book_sales_controller.rb
class BookSalesController < ApplicationController
before_action :find_book_sale, only: %i(show)  
  def index
    @book_sales = BookSale.all
    @book = Book.all
  end

  def new
    @book_sale = BookSale.new
    @books = Book.all
  end

  def create
      @book_sale = BookSale.new(book_sale_params)
    if @book_sale.save
      redirect_to book_sales_path
    else
      redirect_to new_book_sale_path
    end
  end

  def show
    
  end

  private

  def book_sale_params
    params.require(:book_sale).permit(:cust_name, :quantity, :cust_address, :book_id)
  end

  def permitted_params
    params.permit(:id)
  end

  def find_book_sale
    @book_sale = BookSale.find permitted_params['id']  
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :find_book, only: %i[show edit update destroy]

  def index
		@books = Book.all
	end

  def new
    @book = Book.new
    @authors = Author.all
    @categories = Category.all
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      @authors = Author.all
      redirect_to new_book_path
    end
  end

  def edit
    @authors = Author.all
    @categories = Category.all
  end

  def update
    if @book.update(book_params)
      redirect_to books_path
    else
      redirect_to edit_book_path
    end
  end

  def show
  end

  def destroy
    if @book.destroy
      redirect_to books_path
    else
      redirect_to book_path
    end

  end

  private

  def book_params
    params.require(:book).permit(:name, :publication_date, :price, :author_id, :description, :category_id)
  end

  def permitted_params
    params.permit(:id)
  end

  def find_book
    @book = Book.find permitted_params['id']
    
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: %i[show edit update destroy]
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new  
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to categories_path
    else
      flash[:error] = @category.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @category.update(category_params)
      redirect_to categories_path
    else
      render :edit
    end
  end

  def destroy
    if @category.destroy
      redirect_to categories_path
    else
      redirect_to category_path
    end

  end

  private 

  def category_params
    params.require(:category).permit(:cat_name)
  end

  def permitted_params
    params.permit(:id)
  end

  def find_category
    @category = Category.find permitted_params['id'] 
  end
end

app/controllers/publication_houses_controller.rb
class PublicationHousesController < ApplicationController
  before_action :find_publication_house, only: %i[show destroy]
  def index
    @publication_houses = PublicationHouse.all    
  end

  def new
    @publication_house = PublicationHouse.new
  end

  def create
  
    @publication_house = PublicationHouse.new(publication_house_params)
    if(@publication_house.save)
      redirect_to publication_houses_path
    else
      render:new
    end
  end

  def edit
    find_publication_house
  end

  def update
    find_publication_house
    if @publication_house.update(publication_house_params)
      redirect_to publication_house_path
    else
      render :edit
    end
  end
  
  def show
    
  end

  def destroy
    if @publication_house.destroy
      redirect_to publication_houses_path
    else
      redirect_to publication_house_path
    end
    
  end
  private
  def publication_house_params
    params.require(:publication_house).permit(:name, :address, :reg_no, :phone)
  end
  
  def permitted_params
    params.permit(:id)
  end
  def find_publication_house
    @publication_house = PublicationHouse.find permitted_params['id'] 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def custom_bootstrap_flash
    flash_messages = []
    flash.each do |type, message|
      text = "toastr.#{type}(`#{message}`);"
      flash_messages << text.html_safe if message
    end
    flash_messages = flash_messages.join('\n')
    "<script>#{ flash_messages.to_s.html_safe }</script>".html_safe
  end
end

app/helpers/author_helper.rb
module AuthorHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/book_sales_helper.rb
module BookSalesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/publication_houses_helper.rb
module PublicationHousesHelper
end

app/views/authors/_form.html.erb
<%= form_with model: @author do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>
      <ul>
      <% @author.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.text_field :name, value: @author.name, placeholder: "Name" %>
  <%= f.text_field :address, value: @author.address, placeholder: "Address" %>
  <%= f.text_field :pen_name, value: @author.pen_name, placeholder: "Pen name" %>
  <%= f.datetime_field :dob, value: @author.dob, placeholder: "Date of birth" %>
  <%= f.text_field :phone, value: @author.phone, placeholder: "Phone No." %>
  <%= f.collection_select(:publication_house_id, @publication_houses, :id, :name) %></td>
  <%= f.submit action.to_s.upcase %>
  <%= link_to 'Cancel', authors_path %>
<% end %>

app/views/authors/edit.html.erb
<h1>Edit Authors</h1>

<%= render "form", action: "update" %>

app/views/authors/index.html.erb
<center>
  <%= link_to "Books list", books_path %>
  <%= link_to "categories list", categories_path %>
  <%= link_to "publication_houses list", publication_houses_path %>
  <%= link_to "Book Sales list", book_sales_path%>
 

  <br><br>
  <h2>Authors</h2>
  <h3><%= link_to "Create New", new_author_path%></h3>


  <table bgcolor="#B8F4F6" border="1" cellpadding="10" cellspacing="5">
    <tr bgcolor="white">
      <th>Name</th>
      <th>Address</th>
      <th>Pen Name</th>
      <th>Date of Birth</th>
      <th>Phone No.</th>
      <th colspan="3">Actions</th>
    </tr>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.address %></td>
        <td><%= author.pen_name %></td>
        <td><%= author.dob %></td>
        <td><%= author.phone %></td>
        <td><%= link_to "Edit", edit_author_path(author.id) %></td>
        <td><%= link_to "Show", author_path(author.id) %></td>
        <td><%= link_to "Delete", author_path(author.id), method: :delete, data: {confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </table>
</center>

app/views/authors/new.html.erb
<h1>Create Author</h1>

<%= render "form", action: "Create New" %>

app/views/authors/show.html.erb
<h1>Author</h1>
<h2>Name: <%= @author.name%></h2>
<h2>Address: <%= @author.address%></h2>
<h2>Pen Name: <%= @author.pen_name%></h2>
<h2>Date of Birth: <%= @author.dob%></h2>
<h2>Phone No.: <%= @author.phone%></h2>

app/views/book_sales/index.html.erb
<center>
  <%= link_to "Books list", books_path, :class => "btn-link" %>
  <button style = "background: #91D184; border-radius: 20px; font-size: 20px" ><%= link_to "categories list", categories_path %></button>
  <button style = "background: #5CE277; border-radius: 20px; font-size: 20px" ><%= link_to "publication_houses list", publication_houses_path %></button>
  <button style = "background: #B8F4F6; border-radius: 20px; font-size: 20px" ><%= link_to "author list", authors_path %></button>
  
  <br><br>
  <h2>Book Sales</h2>
  <%= link_to "Sale books", new_book_sale_path %>
  <table border="2" bgcolor="#BFD184" cellpadding="10" cellspacing="5">
    <tr bgcolor="white">
      <th>Customer Name</th>
      <th>Address</th>
      <th>Book</th>
      <th>Quantity</th>
      <th>Action</th>
    </tr>
    <% @book_sales.each do |book_sale| %>
      <tr>
        <td><%= book_sale.cust_name %></td>
        <td><%= book_sale.cust_address%></td>
        <td><%= book_sale&.book&.name%></td>
        <td><%= book_sale.quantity %></td>
        <td><%= link_to "Show", book_sale_path(book_sale.id) %></td>
    </tr>
    <% end %>
  </table>
</center>

app/views/book_sales/new.html.erb
<h1>Sale Books</h1>
<%= form_with model: @book_sale do |f| %>
  <%= f.text_field :cust_name, value: @book_sale.cust_name, placeholder: "Customer Name" %>
  <%= f.text_field :cust_address, value: @book_sale.cust_address, placeholder: "Customer Address" %>
    <%= f.collection_select(:book_id, @books, :id, :name) %>
    <%= f.text_field :quantity, value: @book_sale.quantity, placeholder: "Quantity of sales" %>
    <%= f.submit "Sale Books"%>
  <% end %>

app/views/book_sales/show.html.erb
<h1>Book Sale Details</h1>
<table border="5">
  <tr>
    <td>Name of Customer</td>
    <td><%= @book_sale.cust_name%></td>
  </tr>
  <tr>
    <td>Address of customer</td>
    <td><%= @book_sale.cust_address%></td>
  </tr>
  <tr>
    <td>Name of book</td>
    <td><%= @book_sale&.book&.name%></td>
  </tr>
  <tr>
    <td>Quantity of sales</td>
    <td><%= @book_sale.quantity%></td>
  </tr>
</table>

app/views/books/_form.html.erb
<%= form_with model: @book do |f| %>
  <%= f.text_field :name, value: @book.name, placeholder: "Name" %>
  <%= f.datetime_select :publication_date, value: @book.publication_date %>
  <%= f.text_field :price, value: @book.price, placeholder: "Price" %>
  <%= f.collection_select(:author_id, @authors, :id, :name) %>
  <%= f.text_field :description, value: @book.description, placeholder: "Description" %>
  <%= f.collection_select(:category_id, @categories, :id, :cat_name) %>
  
  <%= f.submit action.to_s %>
<% end %>

app/views/books/edit.html.erb
<h1>Edit Book</h1>
<%= render "form",  action: "Update" %>

app/views/books/index.html.erb
<center>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  	<%= link_to "Books list", books_path %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-lg-5 btn-dark ">
      <li class="nav-item active mr-5">
        <%= link_to "publication_houses list", publication_houses_path  %> 
      </li>
        <li class="nav-item active mr-5">
					<%= link_to "author list", authors_path %>      
				</li>
        <li class="nav-item active mr-5">
        	<%= link_to "categories list", categories_path %>
      	</li>
        <li class="nav-item active mr-5">
        	<%= link_to "Book Sales list", book_sales_path %>
      	</li>
      
  </div>
</nav>		
	<br>
	<h2>Books</h2>
	<%= link_to "Add New Book", new_book_path %>
	<table border="1" cellpadding="10" cellspacing="5">
		<tr class="bg-dark text-white text-uppercase text-center" >		
			<th>name</th>
			<th>publication</th>
			<th>publication date</th>
			<th>price</th>
			<th>author</th>
			<th>description</th>
			<th>Category</th>
			<th>Actions</th>
		</tr>
		<% @books.each do |book| %>
			<tr>
				<td><%= book.name %></td>
				<td><%= book.publication %></td>
				<td><%= book.publication_date %></td>
				<td><%= book.price %></td>
				<td><%= book.author.name %></td>
				<td><%= book.description %></td>
				<td><%= book&.category&.cat_name %></td>
				<td><%= link_to "Edit", edit_book_path(book.id), :class => "btn-warning" %>
				<%= link_to "Show", book_path(book.id), :class => "btn-info"%>
				<%= link_to "Delete", book_path(book.id), method: :delete, data: {confirm: "Are you sure?"}, :class => "btn-danger" %></td>
			</tr>
		<% end %>
	</table>
</center>

app/views/books/new.html.erb
<h1>Add Book</h1>
<%= render "form", action: "create" %>

app/views/books/show.html.erb
<h1>Details of book</h1>
<table cellspacing="5" border="2">
  <tr>
    <td>Name</td>
    <td><%= @book.name%></td>
  </tr>
  <tr>
    <td>Publication</td>
    <td><%= @book.publication %></td>
  </tr>
  <tr>
    <td>Publication Date</td>
    <td><%= @book.publication_date%></td>
  </tr>
  <tr>
    <td>Price</td>
    <td><%= @book.price%></td>
  </tr>
  <tr>
    <td>Author</td>
    <td><%= @book.author.name%></td>
  </tr>
  <tr>
    <td>Description</td>
    <td><%= @book.description%></td>
  </tr>
  <tr>
    <td>Category</td>
    <td><%= @book.category.cat_name%></td>
  </tr>
</table>

app/views/categories/_form.html.erb
<%= form_with model: @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :name, 'Category Name' %>
  <%= f.text_field :cat_name, value: @category.cat_name %>
  <%= f.submit action.to_s.upcase %>
  <%= link_to 'Cancel', categories_path %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit new category</h1>

<%= render "form", action: "update" %>

app/views/categories/index.html.erb
<center>
  <button style = "background: grey; border-radius: 20px; font-size: 20px" ><%= link_to "Books list", books_path %></button>
  <button style = "background: #5CE277; border-radius: 20px; font-size: 20px" ><%= link_to "publication_houses list", publication_houses_path %></button>
  <button style = "background: #B8F4F6; border-radius: 20px; font-size: 20px" ><%= link_to "author list", authors_path %></button>
  <button style = "background: #BFD184; border-radius: 20px; font-size: 20px" ><%= link_to "Book Sales list", book_sales_path%></button>
  
  <br><br>
  <h2>
    Category
  </h2>
  <%= link_to "create new category", new_category_path %>

  <table border="2" bgcolor="#91D184" cellpadding="10" cellspacing="5">
    <tr bgcolor="white">
      <th>Name</th>
      <th colspan="3">Action</th>
    </tr>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.cat_name %></td>
        <td><%= link_to "Edit", edit_category_path(category.id)%></td>
        <td><%= link_to "Show", category_path(category.id)%></td>
        <td><%= link_to "Delete", category_path(category.id), method: :delete, data: { confirm: "Are you sure?" }%></td>
      </tr>
    <% end %>
  </table> 
</center>

app/views/categories/new.html.erb
<h1>Create New category</h1>
<%= render "form", action: "create" %>

app/views/categories/show.html.erb
<h1>Category Details</h1>
<h2>Name: <%= @category.cat_name%></h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trial</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= custom_bootstrap_flash %>
    <%= yield %>
  </body>
</html>

app/views/publication_houses/edit.html.erb
<h1>Edit Category</h1>

<%= form_with model: @publication_house do |f| %>
<%= f.text_field :name, value: @publication_house.name %>
<%= f.text_field :address, value: @publication_house.address %>
<%= f.text_field :reg_no, value: @publication_house.reg_no %>
<%= f.text_field :phone, value: @publication_house.phone %>
<%= f.submit "Update" %>
<% end %>

app/views/publication_houses/index.html.erb
<center>
  <button style = "background: grey; border-radius: 20px; font-size: 20px" ><%= link_to "Books list", books_path %></button>
  <button style = "background: #91D184; border-radius: 20px; font-size: 20px" ><%= link_to "categories list", categories_path %></button>
  <button style = "background: #B8F4F6; border-radius: 20px; font-size: 20px" ><%= link_to "author list", authors_path %></button>
  <button style = "background: #BFD184; border-radius: 20px; font-size: 20px" ><%= link_to "Book Sales list", book_sales_path%></button><br><br>
  <h2>
    Publication House<br>
    <%= link_to "Add new Publication House", new_publication_house_path %>
  </h2>
  <table bgcolor="#5CE277" border="2" cellpadding="10" cellspacing="5">
    <tr bgcolor="white">
      <th>Name</th>
      <th>Adderss</th>
      <th>Registration No.</th>
      <th>Phone</th>
      <th colspan="3">Action</th>
    </tr>
    <% @publication_houses.each do |publication_house| %>
      <tr>
        <td><%= publication_house.name %></td>
        <td><%= publication_house.address %></td>
        <td><%= publication_house.reg_no %></td>
        <td><%= publication_house.phone %></td>
        <td><%= link_to "Edit", edit_publication_house_path(publication_house.id) %></td>
        <td><%= link_to "Show", publication_house_path(publication_house.id)%></td>
        <td><%= link_to "Delete", publication_house_path(publication_house.id), method: :delete, data: {confirm: "Are you sure?"} %></td>
      </tr>
    <% end %>
  </table>
</center>

app/views/publication_houses/new.html.erb
<h1>Create New Pubication House</h1>
<h2>Fill up the form</h2>
<%= form_with model: @publication_house do |f| %>
  <%= f.text_field :name, placeholder: "Name of Publication House"%>
  <%= f.text_field :address, :placeholder => "Address"%>
  <%= f.text_field :reg_no, :placeholder => "Registration No."%>
  <%= f.text_field :phone, :placeholder => "Phone No."%>
  <%= f.submit "create" %>
<% end %>

app/views/publication_houses/show.html.erb
<table>
  <tr>
    <td>Name</td>
    <td><%= @publication_house.name %></td>
  </tr>
   <tr>
    <td>Address</td>
    <td><%= @publication_house.address %></td>
  </tr>
   <tr>
    <td>Registration No.</td>
    <td><%= @publication_house.reg_no %></td>
  </tr>
   <tr>
    <td>Phone</td>
    <td><%= @publication_house.phone %></td>
  </tr>

</table>